package com.roger.notebook.dataObject;

public class BookDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_book_category_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_book_category_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_book_category_t.subtitle
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_book_category_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_book_category_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String createtime;

    private Integer uuid;

    public Integer getUuid() {
        return uuid;
    }

    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_book_category_t.bookid
     *
     * @return the value of nb_book_category_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_book_category_t.bookid
     *
     * @param bookid the value for nb_book_category_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_book_category_t.title
     *
     * @return the value of nb_book_category_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_book_category_t.title
     *
     * @param title the value for nb_book_category_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_book_category_t.subtitle
     *
     * @return the value of nb_book_category_t.subtitle
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_book_category_t.subtitle
     *
     * @param subtitle the value for nb_book_category_t.subtitle
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_book_category_t.photo
     *
     * @return the value of nb_book_category_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_book_category_t.photo
     *
     * @param photo the value for nb_book_category_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_book_category_t.createtime
     *
     * @return the value of nb_book_category_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_book_category_t.createtime
     *
     * @param createtime the value for nb_book_category_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}