package com.roger.notebook.dataObject;

public class NoteDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.noteid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private Integer noteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.remark
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.content
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_note_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.noteid
     *
     * @return the value of nb_note_t.noteid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public Integer getNoteid() {
        return noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.noteid
     *
     * @param noteid the value for nb_note_t.noteid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.bookid
     *
     * @return the value of nb_note_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.bookid
     *
     * @param bookid the value for nb_note_t.bookid
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.remark
     *
     * @return the value of nb_note_t.remark
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.remark
     *
     * @param remark the value for nb_note_t.remark
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.title
     *
     * @return the value of nb_note_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.title
     *
     * @param title the value for nb_note_t.title
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.content
     *
     * @return the value of nb_note_t.content
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.content
     *
     * @param content the value for nb_note_t.content
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.photo
     *
     * @return the value of nb_note_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.photo
     *
     * @param photo the value for nb_note_t.photo
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_note_t.createtime
     *
     * @return the value of nb_note_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_note_t.createtime
     *
     * @param createtime the value for nb_note_t.createtime
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}