package com.roger.notebook.dataObject;

public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.UUID
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.phone
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.password
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.avatar
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.nickname
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.sex
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nb_user_t.address
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.UUID
     *
     * @return the value of nb_user_t.UUID
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.UUID
     *
     * @param uuid the value for nb_user_t.UUID
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.phone
     *
     * @return the value of nb_user_t.phone
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.phone
     *
     * @param phone the value for nb_user_t.phone
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.password
     *
     * @return the value of nb_user_t.password
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.password
     *
     * @param password the value for nb_user_t.password
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.avatar
     *
     * @return the value of nb_user_t.avatar
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.avatar
     *
     * @param avatar the value for nb_user_t.avatar
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.nickname
     *
     * @return the value of nb_user_t.nickname
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.nickname
     *
     * @param nickname the value for nb_user_t.nickname
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.sex
     *
     * @return the value of nb_user_t.sex
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.sex
     *
     * @param sex the value for nb_user_t.sex
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nb_user_t.address
     *
     * @return the value of nb_user_t.address
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nb_user_t.address
     *
     * @param address the value for nb_user_t.address
     *
     * @mbggenerated Sun Jul 07 09:12:22 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }
}