package com.roger.notebook.dao;

import com.roger.notebook.dataObject.BookDO;
import java.util.List;

public interface BookDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int deleteByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int insert(BookDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    BookDO selectByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    List<BookDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int updateByPrimaryKey(BookDO record);
}