package com.roger.notebook.dao;

import com.roger.notebook.dataObject.BookDO;
import com.roger.notebook.dataObject.NoteDO;
import java.util.List;
import java.util.Map;

public interface NoteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_note_t
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    int deleteByPrimaryKey(Integer noteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_note_t
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    int insert(NoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_note_t
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    NoteDO selectByPrimaryKey(Integer noteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_note_t
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    List<NoteDO> selectAll(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_note_t
     *
     * @mbggenerated Sun Jul 07 13:05:59 CST 2019
     */
    int updateByPrimaryKey(NoteDO record);

    List<NoteDO> selectNoteListByKeyword(Map map);

    List<NoteDO> selectNoteListByBookId(Map map);

}