package com.roger.notebook.dao;

import com.roger.notebook.dataObject.NoteDO;
import java.util.List;

public interface NoteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int deleteByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int insert(NoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    NoteDO selectByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    List<NoteDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_book_category_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int updateByPrimaryKey(NoteDO record);
}