package com.roger.notebook.dao;

import com.roger.notebook.dataObject.UserDO;
import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_user_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_user_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_user_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    UserDO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_user_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    List<UserDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nb_user_t
     *
     * @mbggenerated Sun Jul 07 00:01:00 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}